### ISSUE TITLE
[Windows 8.1] Session name with accent

### ISSUE THREAD

**Issue by gaetandezeiraud** [relu91/niftyeditor#20]
Hello, 
I am on Windows 8.1 Update 1.
Nifty-Editor V0.5.9.jar when starting a user subfolder with a accent on software crashes when loading.The software starts without a problem when running on the Local Disk (C :).

ScreenShot: http://www.yourphotodropper.aubega.com/images/5bug.png
The loading stuck.

sorry for my bad English.
cordially.

**Comment by relu91** [comment]
Thanks for reporting this! This actually is a bug and I'm going to solve it! :smile: . It 's my bad implementation of class searching fault , but it not should be difficult to get rid of it.
Thanks again, Cris

**Comment by relu91** [comment]
This problem is solved in the 0.5.9 version . :smile:
