### ISSUE TITLE
Only 800x600 is painted

### ISSUE THREAD

**Issue by gterminator** [relu91/niftyeditor#22]
Hi,
on Version 0.5.9 ive got only 800x600 px resolution painted. If i change the resolution to 1024x768 i see that the Rectangle ist bigger. But the Drawcanvas where all the magic is doesnt got changed.

**Comment by relu91** [comment]
Hi! Thank you for using nifty-editor :) . Could you please explain why you close this issue? Has this happened just once ?. Thank you.

**Comment by gterminator** [comment]
i try to change the resolution, mean i type in "1024x768" but the canvas doesnt changed their size. It happens most the time. It only works 1 time..

**Comment by relu91** [comment]
Hi thank you to explain it better, I've tried and in my pc and I saw few times that bug... I don't know why you see it so often ... anyway I'll try to figure out why and solve this issue. By now maximize the window and then minimize it refresh the view and you should see the new resolution. I hope this helps ... 

p.s are you using standalone version or the plug-in in JMonkeyEngine sdk ?
